version: "3.9"
services:
  frontend:
    container_name: frontend
    image: kenytt/ctportal
    ports:
      - 8005:80
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: "2048M"
    restart: always
    pull_policy: always
